### ISSUE TITLE
Kan inte söka på undertaggar om inte huvudtaggen är markerad

### ISSUE THREAD

**Issue by elmaxe** [datasektionen/damm2#16]
**Describe the bug**
Kan inte söka på undertaggar om inte huvudtaggen är markerad

**To Reproduce**
1. Gå till märkesarkiv och sök på en undertagg, ex "ettans"
2. Taggen dyker inte upp
3. Klicka på "mottagningen"-taggen, sök sedan på "ettans"

**Expected behavior**
Ettans ska dyka upp även om mottagningen är omarkerad

**Comment by DouglasFischer** [comment]
Taggsystemet är omarbetat nu.
Använder inte längre under- och huvudtaggar.
